---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/firstdra/public_html
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan config:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan cache:clear
    - chmod -R 755 storage bootstrap/cache
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
