[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"

[healthcheck]
path = "/"
timeout = "30s"