[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd /app && php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"

[healthcheck]
path = "/"
timeout = "30s"