services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: oregon

    dockerfilePath: ./Dockerfile

    ports:
      - port: 8080
        protocol: tcp

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: YOUR_DB_NAME
      - key: DB_USERNAME
        value: YOUR_DB_USERNAME
      - key: DB_PASSWORD
        sync: false
