services:
  - type: web
    name: firstdraft-laravel
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: |
      php artisan config:cache && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: ""
      - key: APP_URL
        value: https://firstdraft.onrender.com # أو الرابط الخاص بك
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d21qchfdiees73e3v9n0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: firstdraftai_db_app_2025
      - key: DB_USERNAME
        value: firstdraftai_db_app_2025_user
      - key: DB_PASSWORD
        value: jZOQeAeOcthIUziK9lLUu0WoXPDssvac

      # Important Laravel defaults
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
