services:
  - type: web
    name: firstdraft
    env: node
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      npm install
      npm run build
    startCommand: |
      php artisan config:cache
      php artisan route:cache
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
