services:
  # Web Service
  - type: web
    name: firstdraft-app
    env: php
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      npm ci
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: FirstDraft
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: firstdraft-app
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_KEY
        generateValue: true

  # Database Service
  - type: pserv
    name: firstdraft-db
    env: postgresql
    plan: free
    disk:
      name: firstdraft-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

databases:
  - name: firstdraft
    databaseName: firstdraft
    user: firstdraft_user
