# render.yaml

services:
  - type: web
    name: laravel-backend
    env: php
    repo: https://github.com/yourusername/your-repo-name
    branch: main
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-backend.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        sync: false

  - type: web
    name: react-frontend
    env: static
    repo: https://github.com/yourusername/your-repo-name
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/build
    headers:
      - source: /*
        headers:
          - key: "Cache-Control"
            value: "max-age=0"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
