services:
  - type: web
    name: firstdraft-laravel
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXx=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromEnvVar: DB_HOST
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromEnvVar: DB_DATABASE
      - key: DB_USERNAME
        fromEnvVar: DB_USERNAME
      - key: DB_PASSWORD
        fromEnvVar: DB_PASSWORD
