# Alternative: Native PHP Configuration (recommended for simplicity)
services:
  # Web Service
  - type: web
    name: firstdraftai2025
    env: php
    plan: free
    healthCheckPath: /up
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      if [ -f package.json ]; then npm ci && npm run build; fi
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: FirstDraftAI
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: firstdraftai2025
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_KEY
        value: "base64:fuYBlHVyLXPuRkpP0mLcJu0PaWR6tVpX9bT7sFiblS0="
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: firstdraftai-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: firstdraftai-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: firstdraftai-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: firstdraftai-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: firstdraftai-db
          property: password
      - key: DB_SSLMODE
        value: require
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: hello@firstdraft.sa
      - key: MAIL_FROM_NAME
        value: FirstDraftAI
      - key: OPENAI_API_KEY
        value: your_openai_key_here
      - key: APP_TIMEZONE
        value: UTC

databases:
  - name: firstdraftai-db
    databaseName: firstdraftai
    user: firstdraftai
