# File: render.yaml
services:
  # Web Service
  - type: web
    name: firstdraftai2025
    runtime: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: FirstDraftAI
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: firstdraftai2025
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: firstdraftai-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: firstdraftai-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: firstdraftai-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: firstdraftai-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: firstdraftai-db
          property: password
      - key: DB_SSLMODE
        value: require
      - key: OPENAI_API_KEY
        value: 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

  # Database Service
  - type: pserv
    name: firstdraftai-db
    runtime: postgresql
    plan: free
    disk:
      name: firstdraftai-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

databases:
  - name: firstdraftai-db
    databaseName: firstdraftai
    user: firstdraftai
