# Fixed render.yaml
services:
  # Web Service
  - type: web
    name: firstdraftai2025
    runtime: docker
    plan: free
    # Add health check configuration
    healthCheckPath: /up
    # Increase timeout for health checks
    buildCommand: docker build -t firstdraftai2025 .
    startCommand: apache2-foreground
    envVars:
      - key: APP_NAME
        value: FirstDraftAI
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://firstdraftai2025.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_KEY
        value: "base64:fuYBlHVyLXPuRkpP0mLcJu0PaWR6tVpX9bT7sFiblS0="
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: firstdraftai-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: firstdraftai-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: firstdraftai-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: firstdraftai-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: firstdraftai-db
          property: password
      # Add SSL configuration for PostgreSQL
      - key: DB_SSLMODE
        value: require
      # Add missing mail configuration
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: hello@firstdraft.sa
      - key: MAIL_FROM_NAME
        value: FirstDraftAI
      # Add missing OpenAI key (redacted in production)
      - key: OPENAI_API_KEY
        value: your_openai_key_here
      # Add missing timezone
      - key: APP_TIMEZONE
        value: UTC

  # Database Service (Fixed)
databases:
  - name: firstdraftai-db
    databaseName: firstdraftai
    user: firstdraftai
    plan: free
