services:
  # Web Service
  - type: web
    name: firstdraftai2025
    env: php
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev --no-interaction
      npm ci --production=false
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: FirstDraftAI
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: firstdraftai2025
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: FirstDraft-DB
          property: connectionString
      - key: APP_KEY
        generateValue: true

databases:
  - name: FirstDraft-DB
    databaseName: firstdraftai_gmbq
    user: firstdraftai_gmbq_user
