services:
  - type: web
    name: firstdraftai2025
    env: php
    buildCommand: composer install --no-dev && npm ci && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: "base64:fuYBlHVyLXPuRkpP0mLcJu0PaWR6tVpX9bT7sFiblS0="
      - key: DATABASE_URL
        fromDatabase:
          name: firstdraftai-db
          property: connectionString
      - key: OPENAI_API_KEY
        value: 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

databases:
  - name: firstdraftai-db
    databaseName: firstdraftai
    user: firstdraftai
